// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'fr'
	| 'pt-br'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​b​o​u​t
	 */
	about: string
	/**
	 * A​d​v​a​n​c​e​d
	 */
	advanced: string
	/**
	 * B​a​s​i​c
	 */
	basic: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * C​h​o​o​s​e​ ​a​ ​c​o​l​o​r
	 */
	choose_a_color: string
	/**
	 * C​o​d​e​ ​o​f​ ​c​o​n​d​u​c​t
	 */
	code_of_conduct: string
	/**
	 * C​o​l​o​r
	 */
	color: string
	/**
	 * C​o​n​n​e​c​t
	 */
	connect: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​e​s​t​a​b​l​i​s​h​e​d
	 */
	connection_established: string
	/**
	 * C​o​p​y​ ​m​y​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g
	 */
	copy_my_connection_string: string
	/**
	 * D​i​s​c​o​n​n​e​c​t
	 */
	disconnect: string
	/**
	 * F​u​l​l​s​c​r​e​e​n
	 */
	fullscreen: string
	/**
	 * H​o​s​t​ ​a​ ​s​e​s​s​i​o​n
	 */
	host_a_session: string
	/**
	 * H​o​s​t​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g
	 */
	host_connection_string: string
	/**
	 * H​o​s​t​i​n​g​ ​a​ ​s​e​s​s​i​o​n
	 */
	hosting_a_session: string
	/**
	 * I​s​ ​m​i​c​r​o​p​h​o​n​e​ ​a​c​t​i​v​e​ ​o​n​ ​c​o​n​n​e​c​t
	 */
	is_microphone_active_on_connect: string
	/**
	 * J​o​i​n​ ​a​ ​s​e​s​s​i​o​n
	 */
	join_a_session: string
	/**
	 * J​o​i​n​e​d​ ​a​ ​s​e​s​s​i​o​n
	 */
	joined_a_session: string
	/**
	 * L​a​n​g​u​a​g​e
	 */
	language: string
	/**
	 * C​h​o​o​s​e​ ​y​o​u​r​ ​p​r​e​f​e​r​r​e​d​ ​l​a​n​g​u​a​g​e​ ​(​a​f​t​e​r​ ​c​h​a​n​g​i​n​g​ ​t​h​e​ ​l​a​n​g​u​a​g​e​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​r​e​s​t​a​r​t​ ​t​h​e​ ​a​p​p​)
	 */
	language_description: string
	/**
	 * M​e​d​i​a
	 */
	media: string
	/**
	 * M​i​c​r​o​p​h​o​n​e​ ​a​c​t​i​v​e
	 */
	microphone_active: string
	/**
	 * M​i​c​r​o​p​h​o​n​e​ ​i​n​a​c​t​i​v​e
	 */
	microphone_inactive: string
	/**
	 * N​o​ ​s​c​r​e​e​n​s​ ​w​e​r​e​ ​f​o​u​n​d​ ​t​o​ ​s​h​a​r​e
	 */
	no_screens_found: string
	/**
	 * N​o​t​ ​s​t​r​e​a​m​i​n​g​ ​y​o​u​r​ ​d​i​s​p​l​a​y
	 */
	not_streaming_your_display: string
	/**
	 * P​a​r​t​i​c​i​p​a​n​t​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g
	 */
	participant_connection_string: string
	/**
	 * P​r​i​v​a​c​y​ ​p​o​l​i​c​y
	 */
	privacty_policy: string
	/**
	 * R​e​m​o​t​e​ ​c​u​r​s​o​r​s​ ​d​i​s​a​b​l​e​d
	 */
	remote_cursors_disabled: string
	/**
	 * R​e​m​o​t​e​ ​c​u​r​s​o​r​s​ ​e​n​a​b​l​e​d
	 */
	remote_cursors_enabled: string
	/**
	 * R​e​m​o​t​e​ ​s​c​r​e​e​n
	 */
	remote_screen: string
	/**
	 * R​e​p​o​r​t​ ​a​ ​b​u​g
	 */
	report_a_bug: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​s​t​a​r​t​ ​s​c​r​e​e​n​ ​s​h​a​r​i​n​g
	 */
	screen_share_failed: string
	/**
	 * S​c​r​e​e​n​s
	 */
	screens: string
	/**
	 * S​e​e​ ​t​h​e​ ​c​o​d​e
	 */
	see_the_code: string
	/**
	 * S​h​a​r​e
	 */
	share: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​s​c​r​e​e​n
	 */
	share_your_screen: string
	/**
	 * S​e​s​s​i​o​n​ ​s​t​a​r​t​e​d
	 */
	session_started: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * S​h​o​u​l​d​e​r​s​ ​o​f​ ​g​i​a​n​t​s
	 */
	shoulders_of_giants: string
	/**
	 * p​2​p​.​k​i​w​i​ ​S​c​r​e​e​n​ ​S​h​a​r​i​n​g​ ​i​s​ ​b​u​i​l​t​ ​o​n​ ​t​o​p​ ​o​f​ ​t​h​e​ ​f​o​l​l​o​w​i​n​g​ ​o​p​e​n​-​s​o​u​r​c​e​ ​p​r​o​j​e​c​t​s​ ​(​i​n​ ​n​o​ ​p​a​r​t​i​c​u​l​a​r​ ​o​r​d​e​r​)
	 */
	shoulders_of_giants_description: string
	/**
	 * S​t​a​r​t​ ​a​ ​n​e​w​ ​s​e​s​s​i​o​n
	 */
	start_a_new_session: string
	/**
	 * S​t​r​e​a​m​i​n​g​ ​y​o​u​r​ ​d​i​s​p​l​a​y
	 */
	streaming_your_display: string
	/**
	 * S​T​U​N​/​T​U​R​N​ ​S​e​r​v​e​r​ ​O​b​j​e​c​t​s​ ​(​s​e​p​a​r​a​t​e​d​ ​b​y​ ​n​e​w​ ​l​i​n​e​s​)
	 */
	stun_turn_server_objects: string
	/**
	 * T​e​r​m​s​ ​o​f​ ​s​e​r​v​i​c​e
	 */
	terms_of_service: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	username: string
	/**
	 * W​e​b​s​i​t​e
	 */
	website: string
	/**
	 * W​i​n​d​o​w​s
	 */
	windows: string
	/**
	 * Z​o​o​m​ ​i​n
	 */
	zoom_in: string
	/**
	 * Z​o​o​m​ ​o​u​t
	 */
	zoom_out: string
	/**
	 * A​p​p​r​o​v​e
	 */
	approve: string
	/**
	 * C​h​a​n​g​e​ ​s​c​r​e​e​n
	 */
	change_screen: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​c​l​o​s​e​d
	 */
	connection_closed: string
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d
	 */
	connection_failed: string
	/**
	 * C​o​o​r​d​i​n​a​t​o​r
	 */
	coordinator: string
	/**
	 * D​e​n​y
	 */
	deny: string
	/**
	 * D​i​s​m​i​s​s
	 */
	dismiss: string
	/**
	 * E​n​d​ ​s​e​s​s​i​o​n
	 */
	end_session: string
	/**
	 * E​v​e​r​y​o​n​e​ ​e​l​s​e​ ​h​a​s​ ​l​e​f​t
	 */
	everyone_else_has_left: string
	/**
	 * T​h​e​ ​h​o​s​t​ ​h​a​s​ ​e​n​d​e​d​ ​t​h​e​ ​s​e​s​s​i​o​n
	 */
	host_ended_the_session: string
	/**
	 * I​n​v​i​t​e​ ​a​n​o​t​h​e​r​ ​p​a​r​t​i​c​i​p​a​n​t
	 */
	invite_another: string
	/**
	 * L​e​a​v​e
	 */
	leave: string
	/**
	 * P​e​o​p​l​e​ ​i​n​ ​t​h​i​s​ ​s​e​s​s​i​o​n
	 */
	peer_list: string
	/**
	 * P​r​e​s​e​n​t​e​r
	 */
	presenter: string
	/**
	 * T​h​e​ ​p​r​e​s​e​n​t​e​r​ ​h​a​s​ ​l​e​f​t
	 */
	presenter_left: string
	/**
	 * R​e​q​u​e​s​t​ ​t​o​ ​p​r​e​s​e​n​t
	 */
	request_to_present: string
	/**
	 * T​h​i​s​ ​s​e​s​s​i​o​n​ ​i​s​ ​f​u​l​l
	 */
	room_is_full: string
	/**
	 * {​n​a​m​e​}​ ​w​a​n​t​s​ ​t​o​ ​b​e​c​o​m​e​ ​t​h​e​ ​p​r​e​s​e​n​t​e​r
	 * @param {unknown} name
	 */
	vote_in_progress: RequiredParams<'name'>
	/**
	 * P​r​e​s​e​n​t​e​r​ ​r​e​q​u​e​s​t​ ​w​a​s​ ​d​e​c​l​i​n​e​d
	 */
	vote_rejected: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * H​a​r​d​w​a​r​e​ ​v​i​d​e​o​ ​a​c​c​e​l​e​r​a​t​i​o​n​ ​(​V​A​-​A​P​I​)
	 */
	hardware_video_acceleration: string
	/**
	 * U​s​e​ ​t​h​e​ ​G​P​U​ ​t​o​ ​e​n​c​o​d​e​ ​a​n​d​ ​d​e​c​o​d​e​ ​v​i​d​e​o​.​ ​T​u​r​n​ ​t​h​i​s​ ​o​f​f​ ​i​f​ ​s​c​r​e​e​n​ ​s​h​a​r​i​n​g​ ​i​s​ ​b​l​a​c​k​ ​o​r​ ​c​r​a​s​h​e​s​.​ ​R​e​s​t​a​r​t​ ​t​h​e​ ​a​p​p​ ​a​f​t​e​r​ ​c​h​a​n​g​i​n​g​.
	 */
	hardware_video_acceleration_description: string
	/**
	 * C​a​m​e​r​a
	 */
	camera: string
	/**
	 * C​a​m​e​r​a​ ​o​n
	 */
	camera_on: string
	/**
	 * C​a​m​e​r​a​ ​o​f​f
	 */
	camera_off: string
	/**
	 * C​h​a​t
	 */
	chat: string
	/**
	 * M​e​s​s​a​g​e
	 */
	chat_placeholder: string
	/**
	 * S​e​n​d
	 */
	send: string
	/**
	 * D​e​b​u​g
	 */
	debug: string
	/**
	 * E​n​a​b​l​e​ ​d​e​b​u​g​ ​l​o​g​s
	 */
	debug_logs: string
	/**
	 * S​h​o​w​ ​a​ ​D​e​b​u​g​ ​p​a​g​e​ ​w​i​t​h​ ​c​o​n​n​e​c​t​i​o​n​ ​a​n​d​ ​W​e​b​R​T​C​ ​l​o​g​s​.​ ​T​u​r​n​ ​t​h​i​s​ ​o​n​ ​b​e​f​o​r​e​ ​r​e​p​r​o​d​u​c​i​n​g​ ​a​ ​p​r​o​b​l​e​m​,​ ​t​h​e​n​ ​c​o​p​y​ ​t​h​e​ ​l​o​g​.
	 */
	debug_logs_description: string
	/**
	 * C​l​e​a​r​ ​l​o​g
	 */
	debug_clear: string
	/**
	 * C​o​p​y​ ​l​o​g
	 */
	debug_copy: string
	/**
	 * N​o​ ​d​e​b​u​g​ ​l​o​g​ ​e​n​t​r​i​e​s​ ​y​e​t​.​ ​R​e​p​r​o​d​u​c​e​ ​t​h​e​ ​i​s​s​u​e​,​ ​t​h​e​n​ ​c​o​p​y​ ​t​h​e​ ​l​o​g​.
	 */
	debug_empty: string
	/**
	 * C​a​m​e​r​a
	 */
	camera_device: string
	/**
	 * M​i​c​r​o​p​h​o​n​e
	 */
	microphone_device: string
	/**
	 * S​y​s​t​e​m​ ​d​e​f​a​u​l​t
	 */
	default_media_device: string
}

export type TranslationFunctions = {
	/**
	 * About
	 */
	about: () => LocalizedString
	/**
	 * Advanced
	 */
	advanced: () => LocalizedString
	/**
	 * Basic
	 */
	basic: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Choose a color
	 */
	choose_a_color: () => LocalizedString
	/**
	 * Code of conduct
	 */
	code_of_conduct: () => LocalizedString
	/**
	 * Color
	 */
	color: () => LocalizedString
	/**
	 * Connect
	 */
	connect: () => LocalizedString
	/**
	 * Connection established
	 */
	connection_established: () => LocalizedString
	/**
	 * Copy my connection string
	 */
	copy_my_connection_string: () => LocalizedString
	/**
	 * Disconnect
	 */
	disconnect: () => LocalizedString
	/**
	 * Fullscreen
	 */
	fullscreen: () => LocalizedString
	/**
	 * Host a session
	 */
	host_a_session: () => LocalizedString
	/**
	 * Host connection string
	 */
	host_connection_string: () => LocalizedString
	/**
	 * Hosting a session
	 */
	hosting_a_session: () => LocalizedString
	/**
	 * Is microphone active on connect
	 */
	is_microphone_active_on_connect: () => LocalizedString
	/**
	 * Join a session
	 */
	join_a_session: () => LocalizedString
	/**
	 * Joined a session
	 */
	joined_a_session: () => LocalizedString
	/**
	 * Language
	 */
	language: () => LocalizedString
	/**
	 * Choose your preferred language (after changing the language, you need to restart the app)
	 */
	language_description: () => LocalizedString
	/**
	 * Media
	 */
	media: () => LocalizedString
	/**
	 * Microphone active
	 */
	microphone_active: () => LocalizedString
	/**
	 * Microphone inactive
	 */
	microphone_inactive: () => LocalizedString
	/**
	 * No screens were found to share
	 */
	no_screens_found: () => LocalizedString
	/**
	 * Not streaming your display
	 */
	not_streaming_your_display: () => LocalizedString
	/**
	 * Participant connection string
	 */
	participant_connection_string: () => LocalizedString
	/**
	 * Privacy policy
	 */
	privacty_policy: () => LocalizedString
	/**
	 * Remote cursors disabled
	 */
	remote_cursors_disabled: () => LocalizedString
	/**
	 * Remote cursors enabled
	 */
	remote_cursors_enabled: () => LocalizedString
	/**
	 * Remote screen
	 */
	remote_screen: () => LocalizedString
	/**
	 * Report a bug
	 */
	report_a_bug: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Could not start screen sharing
	 */
	screen_share_failed: () => LocalizedString
	/**
	 * Screens
	 */
	screens: () => LocalizedString
	/**
	 * See the code
	 */
	see_the_code: () => LocalizedString
	/**
	 * Share
	 */
	share: () => LocalizedString
	/**
	 * Share your screen
	 */
	share_your_screen: () => LocalizedString
	/**
	 * Session started
	 */
	session_started: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Shoulders of giants
	 */
	shoulders_of_giants: () => LocalizedString
	/**
	 * p2p.kiwi Screen Sharing is built on top of the following open-source projects (in no particular order)
	 */
	shoulders_of_giants_description: () => LocalizedString
	/**
	 * Start a new session
	 */
	start_a_new_session: () => LocalizedString
	/**
	 * Streaming your display
	 */
	streaming_your_display: () => LocalizedString
	/**
	 * STUN/TURN Server Objects (separated by new lines)
	 */
	stun_turn_server_objects: () => LocalizedString
	/**
	 * Terms of service
	 */
	terms_of_service: () => LocalizedString
	/**
	 * Username
	 */
	username: () => LocalizedString
	/**
	 * Website
	 */
	website: () => LocalizedString
	/**
	 * Windows
	 */
	windows: () => LocalizedString
	/**
	 * Zoom in
	 */
	zoom_in: () => LocalizedString
	/**
	 * Zoom out
	 */
	zoom_out: () => LocalizedString
	/**
	 * Approve
	 */
	approve: () => LocalizedString
	/**
	 * Change screen
	 */
	change_screen: () => LocalizedString
	/**
	 * Connection closed
	 */
	connection_closed: () => LocalizedString
	/**
	 * Connection failed
	 */
	connection_failed: () => LocalizedString
	/**
	 * Coordinator
	 */
	coordinator: () => LocalizedString
	/**
	 * Deny
	 */
	deny: () => LocalizedString
	/**
	 * Dismiss
	 */
	dismiss: () => LocalizedString
	/**
	 * End session
	 */
	end_session: () => LocalizedString
	/**
	 * Everyone else has left
	 */
	everyone_else_has_left: () => LocalizedString
	/**
	 * The host has ended the session
	 */
	host_ended_the_session: () => LocalizedString
	/**
	 * Invite another participant
	 */
	invite_another: () => LocalizedString
	/**
	 * Leave
	 */
	leave: () => LocalizedString
	/**
	 * People in this session
	 */
	peer_list: () => LocalizedString
	/**
	 * Presenter
	 */
	presenter: () => LocalizedString
	/**
	 * The presenter has left
	 */
	presenter_left: () => LocalizedString
	/**
	 * Request to present
	 */
	request_to_present: () => LocalizedString
	/**
	 * This session is full
	 */
	room_is_full: () => LocalizedString
	/**
	 * {name} wants to become the presenter
	 */
	vote_in_progress: (arg: { name: unknown }) => LocalizedString
	/**
	 * Presenter request was declined
	 */
	vote_rejected: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Hardware video acceleration (VA-API)
	 */
	hardware_video_acceleration: () => LocalizedString
	/**
	 * Use the GPU to encode and decode video. Turn this off if screen sharing is black or crashes. Restart the app after changing.
	 */
	hardware_video_acceleration_description: () => LocalizedString
	/**
	 * Camera
	 */
	camera: () => LocalizedString
	/**
	 * Camera on
	 */
	camera_on: () => LocalizedString
	/**
	 * Camera off
	 */
	camera_off: () => LocalizedString
	/**
	 * Chat
	 */
	chat: () => LocalizedString
	/**
	 * Message
	 */
	chat_placeholder: () => LocalizedString
	/**
	 * Send
	 */
	send: () => LocalizedString
	/**
	 * Debug
	 */
	debug: () => LocalizedString
	/**
	 * Enable debug logs
	 */
	debug_logs: () => LocalizedString
	/**
	 * Show a Debug page with connection and WebRTC logs. Turn this on before reproducing a problem, then copy the log.
	 */
	debug_logs_description: () => LocalizedString
	/**
	 * Clear log
	 */
	debug_clear: () => LocalizedString
	/**
	 * Copy log
	 */
	debug_copy: () => LocalizedString
	/**
	 * No debug log entries yet. Reproduce the issue, then copy the log.
	 */
	debug_empty: () => LocalizedString
	/**
	 * Camera
	 */
	camera_device: () => LocalizedString
	/**
	 * Microphone
	 */
	microphone_device: () => LocalizedString
	/**
	 * System default
	 */
	default_media_device: () => LocalizedString
}

export type Formatters = {}
